timeout: 20m

steps:
- name: 'gcr.io/cloud-builders/kubectl'
  id: 'Code'
  entrypoint: '/bin/bash'
  args:
  - '-xc'
  - echo 'Code analysis'
- name: 'docker'
  id: 'Build'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/booking-client', '.', '-f', 'Dockerfile-qa']
- name: 'docker'
  id: 'TagWithBuildId'
  args: [ 'tag', 'gcr.io/$PROJECT_ID/booking-client', 'gcr.io/$PROJECT_ID/booking-client:$BUILD_ID' ]
- name: 'docker'
  id: 'TagWithCommitSHA'
  args: [ 'tag', 'gcr.io/$PROJECT_ID/booking-client', 'gcr.io/$PROJECT_ID/booking-client:$COMMIT_SHA' ]
- name: 'docker'
  id: 'TagWithShortSHA'
  args: [ 'tag', 'gcr.io/$PROJECT_ID/booking-client', 'gcr.io/$PROJECT_ID/booking-client:$SHORT_SHA' ]
- name: 'docker'
  id: 'BuildBOG'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/bog.booking-client', '.', '-f', 'Dockerfile-prod']
- name: 'docker'
  id: 'TagWithBuildIdBOG'
  args: [ 'tag', 'gcr.io/$PROJECT_ID/bog.booking-client', 'gcr.io/$PROJECT_ID/bog.booking-client:$BUILD_ID' ]
- name: 'docker'
  id: 'TagWithCommitSHABOG'
  args: [ 'tag', 'gcr.io/$PROJECT_ID/bog.booking-client', 'gcr.io/$PROJECT_ID/bog.booking-client:$COMMIT_SHA' ]
- name: 'docker'
  id: 'TagWithShortSHABOG'
  args: [ 'tag', 'gcr.io/$PROJECT_ID/bog.booking-client', 'gcr.io/$PROJECT_ID/bog.booking-client:$SHORT_SHA' ]
- name: 'gcr.io/cloud-builders/kubectl'
  id: 'UnitTest'
  entrypoint: '/bin/bash'
  args:
  - '-xc'
  - echo 'Unit test execution'
- name: 'gcr.io/cloud-builders/kubectl'
  id: 'QADeploy'
  entrypoint: '/bin/bash'
  args:
  - '-xc'
  - if [ $BRANCH_NAME = develop -a $PROJECT_ID = sn-systems ]; then /builder/kubectl.bash set image deployment/booking-client booking-client=gcr.io/$PROJECT_ID/booking-client:$COMMIT_SHA ; else echo "Not a master branch commit, skipping deployment." ; fi
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=sn-cluster-qa'
- name: 'gcr.io/cloud-builders/kubectl'
  id: 'ProdDeploy'
  entrypoint: '/bin/bash'
  args:
  - '-xc'
  - if [ $BRANCH_NAME = master -a $PROJECT_ID = sn-prod ]; then /builder/kubectl.bash set image deployment/bookings bookings=gcr.io/$PROJECT_ID/bog.booking-client:$COMMIT_SHA ; else echo "Not a master branch commit, skipping production deployment." ; fi
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=bog-cluster01'
- name: 'gcr.io/cloud-builders/kubectl'
  id: 'RegressionTest'
  entrypoint: '/bin/bash'
  args:
  - '-xc'
  - echo 'Regression test execution'

images:
- 'gcr.io/$PROJECT_ID/booking-client'
- 'gcr.io/$PROJECT_ID/bog.booking-client'
