FROM node:13.12.0-alpine AS builder

WORKDIR /app

COPY package.json ./
COPY yarn.lock ./

RUN yarn install --ignore-engines

COPY ./ ./

ENV PUBLIC_URL=https://bog.simplenight.com/bookings

RUN yarn build
RUN yarn global add serve

FROM nginx:1.19.3-alpine
RUN mkdir -p /usr/share/nginx/html/bookings
COPY --from=builder /app/build /usr/share/nginx/html/bookings
COPY docker-entrypoint.sh generate_config_js.sh /
RUN chmod +x docker-entrypoint.sh generate_config_js.sh

COPY conf/nginx-prod.conf /etc/nginx/sites-enabled/default
COPY conf/nginx-prod.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

ENTRYPOINT ["/docker-entrypoint.sh"]